name: rnp_front
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  get: 4.6.6
  share_plus: ^7.0.2
  package_info_plus: ^8.0.2
  flame_splash_screen: ^0.2.0
  url_launcher: ^6.1.10
  flutter_map: ^7.0.2
  permission_handler: ^11.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  curved_navigation_bar: ^1.0.3
  intl_phone_field: ^3.1.0
  photo_view: ^0.14.0
  table_calendar: ^3.0.9
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  intl: ^0.19.0
  localstorage: ^4.0.1+2
  flutter_easyloading: ^3.0.5
  open_file_plus: ^3.4.1
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  flutter_svg: ^2.0.10+1
  mobile_scanner: ^6.0.1
  google_maps_flutter: ^2.9.0
  flutter_map_cancellable_tile_provider: ^3.0.2
  geolocator: ^13.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/icons/
    - assets/icons/car/
    - assets/icons/map/
    - assets/icons/money/
    - assets/images/
    - assets/svg_icons/
  fonts:
    - family: DroidArabicKufi
      fonts:
        - asset: assets/fonts/droid_arabic_kufi/Droid.Arabic.Kufi.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 900
