// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfNuuvNBwcAhDhVoMaZEWJoHGTvhTLSNU',
    appId: '1:967034514608:android:bdb15e4fa88c1dd30fa2a9',
    messagingSenderId: '967034514608',
    projectId: 'rnp25-a8a32',
    storageBucket: 'rnp25-a8a32.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhqOxdHy0_3RhMwQ7Qa-mAGkGlVXbDGJ0',
    appId: '1:967034514608:web:3e31c2e6a5ecdd1c0fa2a9',
    messagingSenderId: '967034514608',
    projectId: 'rnp25-a8a32',
    authDomain: 'rnp25-a8a32.firebaseapp.com',
    storageBucket: 'rnp25-a8a32.appspot.com',
    measurementId: 'G-PFVBY33EF1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACkFLt9MPP-pI_LD42Qov0KnLOqMcIIqU',
    appId: '1:967034514608:ios:cc633d6c10c7c9bb0fa2a9',
    messagingSenderId: '967034514608',
    projectId: 'rnp25-a8a32',
    storageBucket: 'rnp25-a8a32.appspot.com',
    iosClientId:
        '967034514608-1u27aenrpfj5jlcphov1iuqj7hlmg1uv.apps.googleusercontent.com',
    iosBundleId: 'com.gremda.rnp-front',
  );
}
